# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Docker Scout
description: List vulnerabilities in images; find better base images and upload an image SBOM to Docker Scout
author: Docker

inputs:
  command:
    required: true
    description: |
      Command(s) to run.
      Use a comma separated list to run several commands on the same set of parameters, for instance quickview,compare
  debug:
    required: false
    description: Debug
  summary:
    required: false
    description: Publish the output as GitHub Action summary
    default: true

  organization:
    required: false
    description: Namespace of the Docker organization
  image:
    required: false
    description: Image to analyze
  platform:
    required: false
    description: Platform of the image to analyze
  ref:
    required: false
    description: Ref if needed

  # compare flags
  to:
    required: false
    description: Image to compare to
  to-ref:
    required: false
    description: Ref of image to compare
  to-stream:
    required: false
    description: Compare to image in stream
    deprecationMessage: Use to-env instead
  to-env:
    required: false
    description: Compare to image in environment
  to-latest:
    required: false
    description: Compare to latest pushed image

  # stream/environment flags
  stream:
    required: false
    description: Name of the stream to record the image
    deprecationMessage: Use environment instead
  environment:
    required: false
    description: Name of the environment to record the image

  # policy flags
  timeout:
    required: false
    description: Maximum time to wait for the policy results to be available

  # filter flags
  ignore-base:
    required: false
    description: Ignore vulnerabilities from base image
  ignore-unchanged:
    required: false
    description: Filter out unchanged packages
  ignore-vex:
    required: false
    description: Filter out CVEs that are marked not affected by a VEX statement
  only-fixed:
    required: false
    description: Filter to fixable CVEs
  only-unfixed:
    required: false
    description: Filter to unfixed CVEs
  only-severities:
    required: false
    description: Comma separated list of severities (critical, high, medium, low, unspecified) to filter CVEs by
  only-package-types:
    required: false
    description: Comma separated list of package types (like apk, deb, rpm, npm, pypi, golang, etc)
  exit-code:
    required: false
    description: Return exit code '2' if vulnerability changes are detected
  exit-on:
    required: false
    description: "(compare only) Return exit code '2' if a condition worsens, options are: vulnerability, policy"

  sarif-file:
    required: false
    description: Write output to a SARIF file for further processing or upload into GitHub code scanning

  dockerhub-user:
    required: false
    description: Docker Hub User
  dockerhub-password:
    required: false
    description: Docker Hub PAT

  # credentials needed to pull private images
  registry-user:
    description: Registry user to pull images
    required: false
  registry-password:
    description: Registry password to pull images
    required: false

  # comments
  github-token:
    description: GitHub Token to write comments
    default: ${{ github.token }}
    required: false
  write-comment:
    description: Write the output as a Pull Request comment
    required: false
    default: true
  keep-previous-comments:
    description: If set, keep but hide previous comment. If not set, keep and update one single comment per job
    required: false

runs:
  using: node16
  main: index.js

branding:
  icon: shield
  color: gray-dark
